export const industries: string[] = [
  "Select your industry",
  "Accommodation and Food Service Activities",
  "Administrative and Support Service Activities",
  "Agriculture, Forestry and Fishing",
  "Arts, Entertainment and Recreation",
  "Construction",
  "Education",
  "Electricity, Gas, Steam and Air Conditioning Supply",
  "Financial and Insurance Activities",
  "Human Health and Social Work Activities",
  "Information and Communication",
  "Manufacturing",
  "Mining and Quarrying",
  "Other Service Activities",
  "Professional, Scientific and Technical Activities",
  "Real Estate Activities",
  "Transportation and Storage",
  "Water Supply; Sewerage, Waste Management and Remediation Activities",
  "Wholesale and Retail Trade",
];
